samples/WebcamAndMicrophoneCapture.java
Complete example for live streaming webcam and audio device capture to either a file or running FMS/Wowza media server
=> WebcamAndMicrophoneCapture.java

samples/RecordActivity.java
I decided to move the check to the surfaceChanged() function as there the camParams was already present and the previewframerate was being set there.
=> Added check for supported display size

src/main/java/org/bytedeco/javacv/FFmpegFrameFilter.java
Replace method "pull" of class FFmpegFrameFilter to fix bug when using
it on Android4.0.
Check https://github.com/bytedeco/javacpp/issues/39 for details.
=> Fix bug when using FFmpegFrameFilter on Android4.0

samples/RecordActivity.java
Keeping a wakelock for the purpose of keeping the screen on can be managed by a single line of XML in your layout. This doesn't require a permission and saves some code.
=> Changed wakelock for keepscreenon in xml

src/main/java/org/bytedeco/javacv/IPCameraFrameGrabber.java
This makes it possible to call `restart` on this frame grabber without throwing a NullPointerException.
Closes #299
=> Fix IPCameraFrameGrabber.stop check for null

src/main/java/org/bytedeco/javacv/IPCameraFrameGrabber.java
- The IPFrameGrabber was allocating new memory on each readImage
this was allocating memory unnessasaraly on the heap. Now it only
allocates new memory if the image size changes.
- The constructor now allows for configuring the connection and
read timeouts for the URLConnection.
- If there is an unexpected end of the stream read image throws
an EOFException instead of returning null.
- Reading data now uses a DataInputStream straight into the pixel
buffer.
- Removes a bunch of unessasary header parsing in start.
- Makes URL and FrameConverter final
Closes #312
Closes #322
=> Cleans up IPFrameGrabber

src/main/java/org/bytedeco/javacv/FrameGrabber.java, src/main/java/org/bytedeco/javacv/IPCameraFrameGrabber.java
- Somehow the @deprecated got removed from the
IPCameraFrameGrabber.
- Adds documentation to FrameGrabber#grab to help clarify how
memory is managed internally.
=> Adds documentation to explain functionality

samples/CaffeGooglenet.java
JavaCV version of the following OpenCV DNN module example
https://github.com/ludv1x/opencv_contrib/blob/master/modules/dnn/samples/caffe_googlenet.cpp
=> JavaCV version of OpenCV caffe_googlenet.cpp

src/main/java/org/bytedeco/javacv/IPCameraFrameGrabber.java
Some cameras send the header with a different case than
the IPCameraFrameGrabber was expecting.
Related https://github.com/WPIRoboticsProjects/GRIP/pull/532
=> Fix IPCameraFrameGrabber reading header wrong

src/main/java/org/bytedeco/javacv/Frame.java
[Frame.java contained a main method](https://github.com/bytedeco/javacv/compare/master...lloydmeta:fix/remove-test-code?expand=1#diff-24eca4907e1892bdc76fcf50eb928138L290) that was supposed to have been deleted.
=> Remove code in Frame.java that should never have been checked in

src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java
eliminate individual get/put calls as much as possible
=> speed optimization on convert(Frame):Bitmap

src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java
Round video width to a multiple of 2 instead of 16 and scale video height to maintain aspect raito.
=> Round video width to a multiple of 2 instead of 16

pom.xml, src/main/java/org/bytedeco/javacv/FrameGrabber.java, src/main/java/org/bytedeco/javacv/RealSenseFrameGrabber.java
This pull request is linked to [this one about librealsense](https://github.com/bytedeco/javacpp-presets/pull/273)
The API is inspired by FreenectFrameGrabber.
Working:
Color stream.
Depth stream.
Limitations:
- No false color for depth.
- No IR
=> New FrameGrabber,  works in external application, not yet in ProCamlib.

src/main/java/org/bytedeco/javacv/OpenCVFrameGrabber.java
OpenCVFrameGrabber .grab() leaks memory and fails the identity test. Fixed by pre-allocating the target Mat.
FrameGrabber grabber = new OpenCVFrameGrabber(0);
grabber.start();
while (true) {
if (grabber.grab() != grabber.grab())
throw new IllegalStateException();
}
=> fixed a memory leak and contract violation

src/main/java/org/bytedeco/javacv/OpenKinectFrameGrabber.java, src/main/java/org/bytedeco/javacv/RealSenseFrameGrabber.java
Hello, 
I made a small update to OpenKinect to get the IR images. 
The Realsense framegrabber is now much more stable. 
Cheers, 
Jeremy.
=> Feature update rs kinect

src/main/java/org/bytedeco/javacv/OpenCVFrameGrabber.java
Fixes #650
Adds the ability to OpenCVFrameGrabber to set the capture format to MJPEG, which (if supported by the webcam) provides much better performance than the default YUY2.
=> Add OpenCVFrameGrabber support for setting capture format (such as MJPG)

src/main/java/org/bytedeco/javacv/FlyCapture2FrameGrabber.java
Add missing functionality to get FlyCapture2FrameGrbber on par with FlyCaptureFrameGrbber.
See also [javacpp-presets PR #400](https://github.com/bytedeco/javacpp-presets/pull/400)
=> Add missing functionality to FlyCapture2FrameGrbber

samples/ImageSegmentation.java
I wrote the JavaCV version of OpenCV imageSegmentation.cpp
[(https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/ImgTrans/imageSegmentation.cpp)]
It may be useful to add it to the samples.
Please notice that I used my own version of `imshow` function, for I'm not able to use the OpenCV original one. Any suggestions?
=> JavaCV version of OpenCV imageSegmentation.cpp

src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java
The code previously did not respect `InputStream.skip()` return value. It leads to wrong seek result because the data might not be skipped to the desired offset.
It also assumed that the maximum input stream size is 1MB which might not be the case for bigger file.  The problem arises when that the data after 1MB offset is read and the mark position is reset. It leads to `InputStream.reset()` not reset to the start of the stream as expected.
This merge requests 
* Respect the InputStream.skip() return value
* Assume the input stream maximum size is at integer maximum.
=> Fix FFmpegFrameGrabber to properly seek/skip the data inside custom InputStream

src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java
`outputStreams.remove(oc);` was called after `oc = null;`, so static outputStreams kept reference to outputStream forever. It's not a big problem in case of file streams, but it becomes a memory leak in case of `ByteArrayOutputStream`.
=> Fixed output streams leaking in FFmpegFrameRecorder

samples/OpenCVFeatures2dSerialization.java, samples/SerializeDeserializeOpenCVDataStructures.java
Added memory and file based OpenCV structure (de)serialization sample
=> OpenCV structure (de)serialization

README.md
It happened to me I searched for latest javacv in maven artifactory. Since artefact javacv exists I copy pasted it into my pom.xml instead of including javacv-platform. I assume this issue can be experienced by more people, thus added a warning in the README.md about being careful the dependency is really what it should be.
=> Please see issue #843 - Improve readme md

src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java
In an audio transcoding operation I noted that final samples were missing in the output file.
So I added the recordMissingSamples() method that takes care of recording final Frame with last missing samples (if any).
This method is called (as first operation) in the stop() method.
=> Added recording of last samples in the final frame

src/main/java/org/bytedeco/javacv/RealSenseFrameGrabber.java
Followin the previous pull request by @andrewsunst, I updated the code for procamcalib. 
https://github.com/bytedeco/javacv/pull/918
In Procamcalib you can set the camera format to : 
* (nothing, or "rgb") Get color Images,
* "ir" - Get IR images. 
* "depth" - Get depth Images (not sure about the rendering yet). 
You can stop - restart the camera, change the resolution.
=> Compatibilty update for procamcalib.

src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java, src/main/java/org/bytedeco/javacv/FrameGrabber.java
Used to set the maxDelay the AVFormat is allowed to cause.
=> (FFmpeg)FrameGrabber: create and use maxDelay

src/main/java/org/bytedeco/javacv/FFmpegFrameFilter.java
=> Fix bug on vflip filter

src/main/java/org/bytedeco/javacv/OpenCVFrameGrabber.java
This is a pull request that exposes the VideoCapture constructor that includes the apiPreference.  I think this is what Spawn32 is looking for in https://github.com/bytedeco/javacv/issues/1021
=> exposing the file with api preference constructor of VideoCapture

README.md
Depending on the version of the maven-compiler plugin the default level was 1.5 prior to plugin version 3.8.0 (https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#source)
Using the source level 1.5 leads to a compile error, when using the pom example to execute the Demo code.
added maven compiler properties to set version of Java source and target explicitelly to 1.6.
=> Update README.md (pom example) due to compile error with Java source level 1.5

CHANGELOG.md, README.md, samples/Demo.java, samples/RealSense2DepthMeasuring.java, src/main/java/org/bytedeco/javacv/FrameGrabber.java, src/main/java/org/bytedeco/javacv/RealSense2FrameGrabber.java
As discussed in #1306 I have implemented a first version of a realsense2 framegrabber. The API is a bit different to the original realsense camera, so I also had to change the API of FrameGrabber.
At the moment it is possible to enable as many streams as the user wants and also specifying custom streams. New frames are loaded through the `trigger()` method, so this method has to be called **before** `grab()`, `grabIR()`, `grabColor()` and so on.
Besides reading the different frames, it is also possible to list all the available cameras.
I have also included a simple example on how to use the depth stream and the mouse to see the distance of the camera at the mouse click position.
The code has been tested with a RealSense D435 on MacOS, but should run with every rs2 compatible device.
=> Implemented realsense2 FrameGrabber for depth, ir and color streams

CHANGELOG.md, src/main/java/org/bytedeco/javacv/FFmpegFrameFilter.java, src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java, src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java
Two robustness features:
* Check if avformat_write_header() was successfull in FFMpegFrameRecorder.start()
* Prevent usage before successfull start() for FFmpegFrame[Filter|Grabber|Recorder]
=> Robustness

.travis.yml
Follows on from the JavaCPP addition, can see from test output its running against ArmV8 which is good to see (that it actually does what was intended!)
Could easily be extended with openjdk 12 + 13 job instances too, maybe marked as failure OK
Had to mark it as a 'shell' type job rather than Java - I think they're still working on those images.
=> Add ARM job to build for testing

CHANGELOG.md, platform/src/test/java/org/bytedeco/javacv/SeekableByteArrayOutputStreamTest.java, src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java, src/main/java/org/bytedeco/javacv/Seekable.java, src/main/java/org/bytedeco/javacv/SeekableByteArrayOutputStream.java, src/main/java/org/bytedeco/javacv/SeekableOutputStream.java
Added a SeekCallback and SeekableOutputStream interface to write e.g. mp4 files into a byte array
As requested in issue #645
=> fix #645 SeekableOutputStream

CHANGELOG.md, src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java, src/main/java/org/bytedeco/javacv/Frame.java
=> Implement reading of other data streams into Frame using FFmpegFrameGrabber #1377

CHANGELOG.md, src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java
Filename variable is set to null after method call 'releaseUnsafe'. In this case, error message will contain "null" instead of filename value. 
Create error message before 'releaseUnsafe'.
=> Fix error message print in FFmpegFrameGrabber

.gitignore, CHANGELOG.md, src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java
Precision of seek to audio or video frames is improved. 
Done after the discussion on issue [#975](https://github.com/bytedeco/javacpp-presets/issues/975).
New code of `setTimestamp` now seeks to the frame just containing the desired timestamp if a specific frame type (video or audio) is requested explicitly (for example, if `setVideoTimestamp` or `setVideoTimestamp` is called).
The old code mostly returned frames next to the frames which should be actually returned (the frames containing the desired timestamps).
Additionally, the new code is ~2x faster when video or audio frames are explicitly requested.
A bug is fixed in `getAudioFrameRate` method as well.
=> [FFmpegFrameGrabber] improved precision of seek to audio or video frames

CHANGELOG.md, samples/YOLONet.java
As requested in #1249  I have created a basic example on how to use YOLO with JavaCV. It runs on CPU and GPU backend and tries to minimize the memory footprint as much as possible.
Not sure if you have a naming convention for the examples? I just called it **YOLONet** in regards to the already existing **CaffeGooglenet** example.
=> Added DNN example for YOLO

CHANGELOG.md, src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java, src/main/java/org/bytedeco/javacv/Frame.java
[https://github.com/bytedeco/javacv/issues/1729](url)
=> Add direct access to frame pict type in Frame Class

CHANGELOG.md, src/main/java/org/bytedeco/javacv/RealSense2FrameGrabber.java
As mentioned in https://github.com/bytedeco/procamcalib/issues/26 this is a small fix for the `RealSense2FrameGrabber` to automatically enable the default color stream (in RGB8 format). The same behaviour is also implemented in the [RealSenseFrameGrabber](https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/RealSenseFrameGrabber.java#L271-L276).
=> Enable default color stream if none is enabled in RealSense2FrameGrabber

CHANGELOG.md, samples/FFmpegStreamingTimeout.java
In FFmpeg 5.0 (bundled with javacv 1.5.7) the option for timeout has been renamed from `stimeout` to `timeout` when using the RTSP protocol. `stimeout` is not a valid option for the RTSP protocol anymore.
- Using it with `FFmpegFrameGrabber` has no effect.
- Using it with [ffmpeg program](http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html) results in error: 
- Unrecognized option 'stimeout'
This PR updates the sample `FFmpegStreamingTimeout` to reflect this change and to make use of the option `timeout` instead.
Using `timeout` with javacv 1.5.7 works as expected for the RTSP sources I have tested with. 
For reference:  
https://github.com/FFmpeg/FFmpeg/commit/6f34f031908b8f16482e951ee5232116fb42b46a
=> Use `timeout` instead of `stimeout` for RTSP.

CHANGELOG.md, src/main/java/org/bytedeco/javacv/FrameGrabber.java
As mentioned in issue #1844, this is my fix to the problem.
When a seek of the source occurs with `FrameGrabber.setTimestamp()` or `FrameGrabber.setFrameNumber()`, the timer should be reset.
If the author of FrameGrabber.grabAtFrameRate(), @wangxi761, can take a look at them. It would be awesome.
=> Update FrameGrabber.java to fix issue #1844

CHANGELOG.md, src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java, src/main/java/org/bytedeco/javacv/FrameGrabber.java
I couldn't get the code to compile due to some missing imports and other errors, but I hope this works. Can you by any chance test this?
#1876
=> Add method to FFmpegFrameGrabber to retrieve attached pic

CHANGELOG.md, src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java
Changes to `setTimestamp` function to resolve issue #2127.
Also improved accuracy of `frameNumber` calculation in `grabFrame` function.
MPEG TS files have a couple of peculiarities: they often start with rather large timestamp values (perhaps as a result of cutting?), and key frames are very frequent. Because of this, jumps to arbitrary frames often occurred with large errors in the previous code. In the new code, `avformat_seek_file` is called repeatedly until a key frame earlier than the desired frame is reached.
=> setTimestamp improvement for MPEG TS files

CHANGELOG.md, src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java
This is the solution for the issue https://github.com/bytedeco/javacv/issues/2119
When release AVFormatContext use avformat_close_input instead of avformat_free_context.
=> bugfix memory leaks

CHANGELOG.md, src/main/java/org/bytedeco/javacv/FFmpegFrameFilter.java, src/main/java/org/bytedeco/javacv/FrameFilter.java
Recently, I created an overlay filter and found that the size of each input and pixelFormat cannot be customized, resulting in incorrect output video. Therefore, I added the following code, which can be modified after the original configuration is generated.
=> [fix] filter: add args modify

CHANGELOG.md, platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java, src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java
Fix for #2074. Add a retry mechanism. The test that was modified was asserting incorrectly, since the expected amerge behavior is to add the channels to the file if both the input files are stereo.
=> #2074 Fix dropped frames at the end of encoders that buffer more than one packet.

CHANGELOG.md, pom.xml, src/main/java/org/bytedeco/javacv/LibgdxFrameConverter.java
Add LibgdxFrameConverter class to convert Frame to Libgdx Pixmap.
=> Add LibgdxFrameConverter class to convert Frame to Libgdx Pixmap
