bytedeco/javacv

- samples/ColoredObjectTrack.java
Hello guys
Just an example using the opencv to make a colored object tracking, i adpted this code to bytedeco/javacv, i think this will help some people.
Hugs for all
> Added Colored Object Track Example using webcam

- samples/OpticalFlowDense.java
> Moved from deprecated getFloatBuffer() to current createBuffer()

- src/main/java/org/bytedeco/javacv/OpenCVFrameGrabber.java
As requested, this is my attempt at upgrading `OpenCVFrameGrabber` to use the new VideoCapture C++ API. A few caveats:
- ~~I couldn't test this at all; can't figure out how to get the dependencies to download. The IDE is happy with me adding Sonatype snapshots as a new repository, but `mvn` gave me the `Failed to execute goal on project javacv: Could not resolve dependencies for project org.bytedeco:javacv:jar:1.2-SNAPSHOT...`~~ I tested by using older non-snapshot dependencies and a very basic this with a very basic webcam to `CanvasFrame` program
- I'm not sure if this will actually help with @PhilAndrew 's problem on Windows10.
- Upgrade OpenCVFrameGrabber to use the new C++ VideoCapture API
- ~~Add a mention for SBT-OpenCV~~
> Refs #357: Upgrade to VideoCapture API

- samples/PrincipalComponentAnalysis.java
> Added PCA sample

- samples/PacketRecorderTest.java
- src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java
- src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java
https://code.google.com/archive/p/javacv/issues/456
> Ability to do a direct stream copy of audio and / or video instead of re-encoding

- samples/OpenCVFaceRecognizer.java
This will replace deprecated calls and stop calling the entire OpenCV backend as static.
> OpenCVFaceRecognizer: Improve efficiency

- samples/BioInspiredRetina.java
Bioinspired Retina demonstration, depends uppon pullrequest #282 javacpp-presets.
> Added Retina demonstration

- samples/TemplateMatching.java
Copied template matching from pull and fixed formatting
> Formatting update

- pom.xml
I think this should be fine but still waiting for it to build, so can't say 100% tested yet. javacpp build went fine though.
> update maven assembly plugin

- pom.xml
Version updates of maven plugins to support building with openjdk9
> update maven plugins for openjdk9

- pom.xml
- src/main/java/org/bytedeco/javacv/OpenKinect2FrameGrabber.java
Hello, 
I created a frameGrabber for OpenKinect2. It is not completely stable but works to get color or depth images. 
There is also a pull request for Javacpp-presets for libfreenect2. 
Cheers, 
Jeremy.
> new added OpenKinect2FrameGrabber.

- src/main/java/org/bytedeco/javacv/RealSenseFrameGrabber.java
There was an issue about choosing which camera to activate. 
Discussion with @mattdibi there: https://github.com/bytedeco/javacv/issues/669 .
> Fixed the problem of accessing the device before it was instanciated.

- samples/DeinterlacedVideoPlayer.java
A sample for FFmpegFrameFilter - the frames are deinterlaced with yadif (the bgr24 format is specified into the ffmpeg filter string)
> Sample FFmpegFrameFilter - yadif deinterlacing

- samples/CaffeGooglenet.java
See https://github.com/opencv/opencv_contrib/issues/749
> CaffeGooglenet.java sample should use Blob.fromImages(img) instead of new Blob(img)

- src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java
https://github.com/bytedeco/javacv/issues/870
> Force setup doAudio=true

- src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java
- src/main/java/org/bytedeco/javacv/FrameRecorder.java
Introduce and set the 3 new parameters maxBFrames, trellis and maxDelay.
> (FFmpeg)FrameRecorder: Add new settings

- samples/DeepLearningFaceDetection.java
This example does face detection using deep learning model which provides a great accuracy compared to OpenCV face detection using Haar cascades.
> add face detection example using deep learning model

- CHANGELOG.md
- src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java
- src/main/java/org/bytedeco/javacv/Java2DFrameConverter.java
Hi, 
There is the "rebase" (was easier to fork again..)
[Conversation history here](https://github.com/bytedeco/javacv/pull/1162/)
> Concurrency issue

- src/main/java/org/bytedeco/javacv/OpenCVFrameGrabber.java
- src/main/java/org/bytedeco/javacv/OpenCVFrameRecorder.java
Added documentation regarding available keys for setOption in OpenCVFrameGrabber OpenCVFrameRecorder
> Added reference to opencv_videoio in documentation for setOption

- CHANGELOG.md
- samples/RealSense2DepthMeasuring.java
- src/main/java/org/bytedeco/javacv/RealSense2FrameGrabber.java
Found a bit of time to update the rs2-framegrabber and also to write a short [wiki page](https://github.com/bytedeco/javacv/wiki/RealSense2FrameGrabber). 
This update fixes some problems when using multiple devices and multiple streams and adds support for setting sensor options.
> Updated realsense2 framegrabber

- CHANGELOG.md
- src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java
1. Fixed condition for no-sound video recording
> #1082. Fixed JVM crash

- CHANGELOG.md
- src/main/java/org/bytedeco/javacv/FFmpegFrameFilter.java
Add location to String.format to avoid LTR languages number exception.
> Add location to String.format

- CHANGELOG.md
- src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java
> when fps<1,num()/den() will be zero

- CHANGELOG.md
- samples/Similarity.java
add image similarity measurement code.
reference code: https://docs.opencv.org/master/d5/dc4/tutorial_video_input_psnr_ssim.html
> add similarity sample

- CHANGELOG.md
- src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java
> Override getVideoCodecName() method inside FFmpegFrameGrabber

- platform/pom.xml
- pom.xml
I bumped up various versions of maven plugins and also bumped the source and target versions from 1.7 to 1.8 properties of maven-compiler-plugin.
> Upgraded various maven plugins to their latest versions.
